### ISSUE TITLE
Please help BETA test: Auto-indent new lines using `cljfmt`

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva-fmt#1]
In order to have consistent indent decisions within Calva Formatter I have made a version that uses the same formatter and the same configuration for both the auto-indent of new lines and for reformatting of code (wether it be manually or on paste/save).

However, since the auto-indent of new lines now means formatting text to find out how the new line should be indented, it can be a bit slow. Especially for big chunks of text. In this version the text being formatted is the enclosing top level form (often a `defn` or similar), so this could still be too slow for large functions. Therefore this BETA test.

To help me try this out, please install the attached VSIX package manually in VS Code.

*You need to rename the extension from `zip` to `vsix`*, since Github would not let me attach VSIX files (which happen to be ZIP files internally).

[calva-fmt-0.0.4-WIP.zip](https://github.com/BetterThanTomorrow/calva-fmt/files/2130696/calva-fmt-0.0.4-WIP.zip)

Please let me know in a comment if you are testing. And, of course, also let me know how the testing is working out there.

Many thanks in advance! ❤️

**Comment by PEZ** [comment]
And here is a version that most often formats less text and thus is faster. 

[calva-fmt-0.0.4-WIP-B2.zip](https://github.com/BetterThanTomorrow/calva-fmt/files/2132265/calva-fmt-0.0.4-WIP-B2.zip)

(Again, change extension to `.vsix` to try it out.)

**Comment by ajoberstar** [comment]
Let me know if this should be a different issue. I'm seeing this with the marketplace version and this VSIX.

The indentation is a little weird in this case. It keeps doing this:

```clojure
(defui Candidate
  static om/Ident
  (ident [this {:keys [name]}]
         [:candidate/by-name name])
  Object
  (render [this]
          (let [{:keys [name]} (om/props this)]
            (dom/li nil name))))
```

When I want this:

```clojure
(defui Candidate
  static om/Ident
  (ident [this {:keys [name]}]
    [:candidate/by-name name])
  Object
  (render [this]
    (let [{:keys [name]} (om/props this)]
      (dom/li nil name))))
```

I do also have Parinfer installed (which I know is in a slightly odd state right now).

**Comment by PEZ** [comment]
So, `ident` and `render` are macros that you would like special indent for? This is partly why I am trying to make this change. With the current/published on type indent adjustment this would have been a rather easy fix, but then the document/selection formatter would have reformatted it differently anyway.

I think this might be possible to solve using `cljfmt` options, at least I will give it a try. There is also [this feature request](https://github.com/weavejester/cljfmt/issues/49) on `cljfmt` which would be a more sustainable way to address the issue from a community viewpoint. Than each formatter wouldn't have to keep tabs on all the macros out there and their preferred indentation.

Yes, it would be nice with an issue on its own for this particular thing with `ident` and `render`.

**Comment by PEZ** [comment]
Here's a third VSIX (named `.zip` so rename):

[calva-fmt-0.0.4-WIP-B3.zip](https://github.com/BetterThanTomorrow/calva-fmt/files/2137667/calva-fmt-0.0.4-WIP-B3.zip)

It *should* behave just like B2, but it is a rather big rewrite of the code, so that I could do more of the work in ClojureScript and less in TypeScript. Please let me know if it seems to behave.

**Comment by ajoberstar** [comment]
@PEZ `defui` is roughly like a `defrecord`, so `ident` and `render` are more like methods I'm implementing on a protocol.

I'll probably see if cljfmt on its own is the same behavior (which I imagine it is). If not, I'll open a new issue though. Thanks.

**Comment by PEZ** [comment]
Alright, so this is now released. Thanks!
