### ISSUE TITLE
`Format and align current format` support for `let`-style bindings

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva-fmt#14]
So that let and similar macros (none comes to mind now) can be aligned
eg:
```
(let [a 1
      bar 2] ...)
```
becomes
```
(let [a   1
      bar 2] ...)
```

**Comment by PEZ** [comment]
There is a command *Format and Align Current Form* that does this. Default keybinding is `alt+ctrl+l`. It sometimes does pretty weird things and works recursively down the code structure, so use it with precision.

Hopefully we will be able to support this in a more on-the-fly way, but for now this is what we have. Please let me know if works for you.

**Comment by mseddon** [comment]
This is something that the indent on newline doesn't currently support, but I can envision something that would detect this case and continue automatically, which actually may be pretty cool! In the meantime you can post hoc tweak the indent as pez suggests, which works well.

**Comment by claynon** [comment]
It just notice that it does work, but not in the way I was expecting.
When the cursor is inside the let binding array and I `alt+ctrl+l` the array isn't aligned, but when the cursor is outside the array (before or after the array, but still inside the let construct) `alt+ctrl+l` works.

Is this the expected behavior?

**Comment by PEZ** [comment]
It is quite expected. 😄 Even if it is not optimal. The reason it is expected is that the command only gets the ”current form” (the closest form enclosed by some brackets) to format. If you run it from within the bindings box, the formatter won't see the `let` form and thus will not know to align stuff.

**Comment by claynon** [comment]
Got it. Now that I know how it woks I'm getting used to it
Thank you :)
