### ISSUE TITLE
Formatting error with :or

### ISSUE THREAD

**Issue by callwait** [BetterThanTomorrow/calva-fmt#15]
With next code:
```
(defn main []
  (let [{:keys [y]
         :or   {y true}} x
        {:keys [z]}      x]))
```

I got bad formating

```
(defn main []
  (let [{:keys [y]
         :or   {y true}} x
        {:keys [z]}               x]))
```
I think it doesn't count the line break before  :or
Thanks!

**Comment by PEZ** [comment]
Hello. Is this with the *Format and Align Current Form* command?

**Comment by callwait** [comment]
Hi, yeah with it

**Comment by PEZ** [comment]
Thanks for reporting this. It will take us a while to fix it, but we'll get there. :smile: The reason it will take a while is that we are in the process of switching out the formatting engine for one that we have written ourselves (or, rather, @mseddon has written it) and then this whole alignment story will look totally different and be easier to get in control of.

**Comment by callwait** [comment]
Thank you, I had switched from IntelliJ + cursive to vscode+calva, calva works much better except that thing

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
