### ISSUE TITLE
Problem on formating current namespace namespaced keyword

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva-fmt#16]
Formating a `current namespace namespaced keyword` (i.e. keyword with `::`) is not working
```
{:foo 1
 ::barbaz 2
```
after format and align should be
```
{:foo     1
 ::barbaz 2
```
but it happens nothing when I hit `shift+ctrl+l`

**Comment by PEZ** [comment]
Yes, this is a sad state of affairs. It is related to this issue on rewrite-cljs: https://github.com/clj-commons/rewrite-cljs/issues/14

For a long while there seemed to be little hope of getting it fixed, but as you can see on the url, rewrite-cljs is now under the umbrella of CLJ Commons and @lread had started working on this particular issue, from the clj-rewrite end.

Hope is also coming from @mseddon 's work with a new formatting engine for Calva. So either way this is going to get fixed, I think. Even if it could take a while.

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
