### ISSUE TITLE
Doesn't use configuration settings

### ISSUE THREAD

**Issue by dijonkitchen** [BetterThanTomorrow/calva-fmt#3]
`cljfmt` has a bunch of [configuration settings](https://github.com/weavejester/cljfmt#configuration) you can add to your `project.clj`. 

When I have something like `:cljfmt {:indents {fn-traced [[:inner 0]]}}` in my dev profile, the `cljfmt` built-in to Calva doesn't recognize this customization and formats normally. 

This can cause a large diff when existing files using `lein cljfmt fix` utilize the proper configuration.

**Comment by PEZ** [comment]
This is a very good point. Maybe I can try pick those configs up and merge them with the config in the extension settings.

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
