### ISSUE TITLE
Issue with CRLF line endings

### ISSUE THREAD

**Issue by mseddon** [BetterThanTomorrow/calva-fmt#6]
Following our discussion on slack, I've isolated the indent issue to CRLF line endings.

Calva Formatter 0.0.17, Calva Paredit 0.1.20, Calva 1.3.49:

Set the line ending to CRLF. Enter the following, (_ indicates the caret position):
```
(defn foo[x]_)
```

When you press return, the result is:
```
(defn foo [x]
 _ )
```

With LF line endings, the result is correct:
```
(defn foo [x]
  _)
```

**Comment by PEZ** [comment]
While this is being sorted out, should we advice Windows users to set line endings to just NL? What are the tradeoffs?

**Comment by icooper** [comment]
Changing line endings to LF (using `"files.eol": "\n"` in settings.json) does work around the issue.

**Comment by mseddon** [comment]
For now that will probably work. I will try running with this and report any issues I hit here.

**Comment by mseddon** [comment]
I think this is fixed now.
